name: Build Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
          pip install "paddleocr>=2.0.1" -i https://mirror.baidu.com/pypi/simple
          pip install pyinstaller
#          pip install -r requirements.txt
          

      - name: Build package
        run: python build.py

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ppocr-tool-${{ runner.os }}-${{ runner.arch }}
          path: dist

  # build_macos_m2:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.7

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install pyinstaller

  #     - name: Build package
  #       run: pyinstaller -F main.py

  #     - name: Upload package
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: doc-search-${{ runner.os }}-${{ runner.arch }}
  #         path: dist

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
          pip install "paddleocr>=2.0.1" -i https://mirror.baidu.com/pypi/simple
          pip install pyinstaller
#          pip install -r requirements.txt
          

      - name: Build package
        run: python build.py

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ppocr-tool-${{ runner.os }}-${{ runner.arch }}
          path: dist

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
          pip install "paddleocr>=2.0.1" -i https://mirror.baidu.com/pypi/simple
          pip install pyinstaller
#          pip install -r requirements.txt
          

      - name: Build package
        run: python build.py

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ppocr-tool-${{ runner.os }}-${{ runner.arch }}
          path: dist